### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by ivanjaros** [asticode/goav#1]
[REPOST](https://github.com/asticode/go-astiencoder/issues/4)
~Since goav has disabled issues i will ask in here:~
I have few income streams(srt->ts->h264/aac, rtmp->flv->h264/aac,...) that i need to "normalize" into av1 and then create different quality versions(ie 240p, 360p, 4801p, 720p and 1080p). I am looking at goav but I am not seeing functions that look like they will do what I am after.

Can you hint at where to begin? I will most likely have the input codec info so I do not need to guess the codec or the container to begin with. I just need to take the packets and transcode them from codec A to codec B and that is about it.

For example I have
avCtx := avformat.AvformatAllocContext()
avCtx.AvformatNewStream()

but there is no way to get the AvCodec to pass to the new stream method so I am stuck right from the get go.

**Comment by asticode** [comment]
I see 2 options :

1) Checkout [ffmpeg examples](https://github.com/FFmpeg/FFmpeg/tree/master/doc/examples) and see which functions should be called, when and where
2) Checkout [my GO encoder](https://github.com/asticode/go-astiencoder) that uses `goav`. It's not perfect, but it aims at simplifying the use of `goav` by splitting your workflow by feature (demux, decode, filter, encode, mux, etc.). You can start by looking at the [out-of-the-box encoder](https://github.com/asticode/go-astiencoder/tree/master/astiencoder).

**Comment by ivanjaros** [comment]
this looks useful https://github.com/leandromoreira/ffmpeg-libav-tutorial
